In [1]:
import numpy as np

In [2]:
#arrray creation

In [3]:
#zero dimension array
a=np.array(5)
a

array(5)

In [4]:
#one dimensional array
b=np.array([1,2,3])
print(b)


[1 2 3]


In [5]:
b

array([1, 2, 3])

In [6]:
#two dimensional array
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
#3 dimensional array
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [9]:
e=np.array("Gopi")
e

array('Gopi', dtype='<U4')

In [10]:
print(e)


Gopi


In [11]:
f=np.array(['swea','noura'])
print(f)

['swea' 'noura']


In [12]:
f

array(['swea', 'noura'], dtype='<U5')

In [13]:
g=np.array([['swea','noura'],['gopi','shaheen']])
print(g)

[['swea' 'noura']
 ['gopi' 'shaheen']]


In [14]:
h=np.array([[['swea','noura'],['gopi','shaheen']],[['swea','noura'],['gopi','shaheen']]])
h

array([[['swea', 'noura'],
        ['gopi', 'shaheen']],

       [['swea', 'noura'],
        ['gopi', 'shaheen']]], dtype='<U7')

In [15]:
print(h)

[[['swea' 'noura']
  ['gopi' 'shaheen']]

 [['swea' 'noura']
  ['gopi' 'shaheen']]]


In [16]:
#array of zeros

i=np.zeros((2,3))
print(i)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
#array of ones

j=np.ones((2,3))
print(j)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# even numbers

k=np.arange(0,10,3)
print(k)

[0 3 6 9]


In [19]:
#5 values between respective numbers

l=np.linspace(0,1,5)
print(l)

[0.   0.25 0.5  0.75 1.  ]


In [20]:
#shape(rows,columns)

m=np.array([[1,2,3],[4,5,6]])
print(m)
print(m.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
#no. of dimensions
print(m.ndim)

2


In [22]:
#data type
print(m.dtype)

int64


In [23]:
#indexing
print(m[0,1])

2


In [24]:
#slicing
print(b[1:3])

[2 3]


In [25]:
#add scalar
print(m+5)

[[ 6  7  8]
 [ 9 10 11]]


In [26]:
#multiplying
print(m*2)

[[ 2  4  6]
 [ 8 10 12]]


In [27]:
#element wise addition
print(b+m[0])

[2 4 6]


In [28]:
#matrix multiplication
print(np.dot(c,m.T)) #dimension 2x3 ; 3x2

[[14 32]
 [32 77]]


In [29]:
print(c.shape)
print(m.shape)

(2, 3)
(2, 3)


In [30]:
#sum of elements
print(np.sum(m))

21


In [31]:
#average
print(np.mean(m))

3.5


In [32]:
#max value
print(np.max(m))

6


In [33]:
#square root
print(np.sqrt(m))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [34]:
n=np.arange(6).reshape(2,3)
print(n)

[[0 1 2]
 [3 4 5]]
